# This is a basic workflow to help you get started with Actions

name: Study_Action

# Controls when the workflow will run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        shell: bash
        run: |
          count=$(cat README.md | sed '/^$/d' | wc -l)
          a=$(($count / 2))
             if [[ $a = 0 ]]
              then
                echo "success"
              else
                exit 1
             fi
             done
